/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lee_livesdk_RtmpMuxer */

#ifndef _Included_com_example_lee_livesdk_RtmpMuxer
#define _Included_com_example_lee_livesdk_RtmpMuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    open
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpMuxer_open
  (JNIEnv *, jobject, jstring, jint, jint,jobject);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    writeVideo
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpMuxer_writeVideo
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    writeAudio
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpMuxer_writeAudio
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpMuxer_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpMuxer_close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    write_flv_header
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_example_lee_livesdk_RtmpMuxer_write_1flv_1header
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    file_open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_lee_livesdk_RtmpMuxer_file_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    file_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lee_livesdk_RtmpMuxer_file_1close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lee_livesdk_RtmpMuxer
 * Method:    isConnected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpMuxer_isConnected
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
