/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lee_livesdk_RtmpClient */

#ifndef _Included_com_example_lee_livesdk_RtmpClient
#define _Included_com_example_lee_livesdk_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_lee_livesdk_RtmpClient_OPEN_SUCCESS
#define com_example_lee_livesdk_RtmpClient_OPEN_SUCCESS 1L
/*
 * Class:     com_example_lee_livesdk_RtmpClient
 * Method:    nativeAlloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_lee_livesdk_RtmpClient_nativeAlloc
        (JNIEnv *, jobject);

/*
 * Class:     com_example_lee_livesdk_RtmpClient
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;ZJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpClient_nativeOpen
        (JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     com_example_lee_livesdk_RtmpClient
 * Method:    nativeRead
 * Signature: ([BIIJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpClient_nativeRead
        (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     com_example_lee_livesdk_RtmpClient
 * Method:    nativeWrite
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_lee_livesdk_RtmpClient_nativeWrite
        (JNIEnv *, jobject, jbyteArray, jint, jlong);

/*
 * Class:     com_example_lee_livesdk_RtmpClient
 * Method:    nativePause
 * Signature: (ZJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lee_livesdk_RtmpClient_nativePause
        (JNIEnv *, jobject, jboolean, jlong);

/*
 * Class:     com_example_lee_livesdk_RtmpClient
 * Method:    nativeIsConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_lee_livesdk_RtmpClient_nativeIsConnected
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_lee_livesdk_RtmpClient
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_lee_livesdk_RtmpClient_nativeClose
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
